name: SRVerify
version: ${project.version}
main: me.delected.srverify.SRVerify
api-version: 1.16
authors: [Delected_]

commands:
  verify:
    usage: /verify
    description: Command to initate the verification of the user.
